version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: own_dca_db
    volumes:
      - myowndca_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: my-own-dca
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/my-own-dca
      - migrations:/my-own-dca/dca/migrations
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  myowndca_data:
  migrations:
